---
# =============================================================================
# ArgoCD Application — Synchronizes Kubernetes manifest to cluster
# =============================================================================

# We can consider this file is the contract for argocd to have permission 
# to mangage infrastructure of this cluster 


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris-staging
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/lamelihuynh/tetris-infra.git
    targetRevision: main
    path: kubernetes/overlays/staging
  
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  
  syncPolicy:
    automated:
      prune: true      # Delete resources not in repo
      selfHeal: true   # Re-sync if cluster drift detected (admin edit k3d infrastructure, argocd will detect and rewrite infra from git down - only trust single source )
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
