apiVersion: v1
kind: Service
metadata:
  name: tetris
spec:
  selector:
    app: tetris
  ports:
    - protocol: TCP
      port: 80           # Cổng ảo bên ngoài (để gõ trên trình duyệt)
      targetPort: 80   # Cổng thật bên trong Pod (Node.js đang chạy)