apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
images:
- name: tetris-devsecops
  newName: localhost:5001/devsecops/tetris
  newTag: 1dba575f066c
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: tetris
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: tetris-staging.localhost
  target:
    kind: Ingress
    name: tetris
