FROM jenkins/jenkins:lts-jdk17

USER root
RUN apt-get update && \
    apt-get install -y docker.io curl unzip awscli && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
COPY ./ci/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt